### ISSUE TITLE
script cache clear error 255

### ISSUE THREAD

**Issue by Zt-freak** [vQFire/MBORijnland#8]
```Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineCacheBundle" from namespace "Doctrine\Bundle\DoctrineCacheBundle".
!!  Did you forget a "use" statement for another namespace? in C:\xampp\htdocs\MBORijnland\src\Kernel.php:23
!!  Stack trace:
!!  #0 C:\xampp\htdocs\MBORijnland\vendor\symfony\http-kernel\Kernel.php(429): App\Kernel->registerBundles()
!!  #1 C:\xampp\htdocs\MBORijnland\vendor\symfony\http-kernel\Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 C:\xampp\htdocs\MBORijnland\vendor\symfony\framework-bundle\Console\Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 C:\xampp\htdocs\MBORijnland\vendor\symfony\framework-bundle\Console\Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 C:\xampp\htdocs\MBORijnland\vendor\symfony\console\Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Co in C:\xampp\htdocs\MBORijnland\src\Kernel.php on line 23
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineCacheBundle" from namespace "Doctrine\Bundle\DoctrineCacheBundle".
!!  Did you forget a "use" statement for another namespace? in C:\xampp\htdocs\MBORijnland\src\Kernel.php:23
!!  Stack trace:
!!  #0 C:\xampp\htdocs\MBORijnland\vendor\symfony\http-kernel\Kernel.php(429): App\Kernel->registerBundles()
!!  #1 C:\xampp\htdocs\MBORijnland\vendor\symfony\http-kernel\Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 C:\xampp\htdocs\MBORijnland\vendor\symfony\framework-bundle\Console\Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 C:\xampp\htdocs\MBORijnland\vendor\symfony\framework-bundle\Console\Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 C:\xampp\htdocs\MBORijnland\vendor\symfony\console\Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Co in C:\xampp\htdocs\MBORijnland\src\Kernel.php on line 23
!!
Script @auto-scripts was called via post-update-cmd```

**Comment by vQFire** [comment]
Zelfde als bij #6

**Comment by vQFire** [comment]
Volgens de [github](https://github.com/doctrine/DoctrineCacheBundle#deprecation-warning) van de Doctirne Cache Bundle wordt deze bundle niet meer geüpdate.

**Comment by vQFire** [comment]
Found the error.  
In de `composer.json` zit 2 keer de `require-dev` object. Dit zorgt ervoor dat veel onderdelen niet geïnstalleerd worden. Dit is op te lossen door de 2e (ook de kleinste) `require-dev` te verwijderen. Dan moet je ook je `composer.lock` verwijderen.  

Als je dit gedaan hebt moet je in `config/routes.yaml` het gedeelte `<<<<<< HEAD` weghalen. Er staat ook zo'n `HEAD` in `base.html.twig` en eentje in de `.gitignore`.  

Wanneer je dit allemaal hebt gedaan doe je `composer install` en dan zal alles moeten werken 👍
